import { RentalList } from "./_types";

export const SAMPLE_RENTAL_DATA: RentalList = [
    {
        id: "1",
        name: "Cozy Apartment in Paco",
        location: "Paco, Manila",
        price: 15000,
        images: ["/room.jpg", "/room.jpg", "/room.jpg"],
        propertyType: "Apartment",
        bedrooms: 2,
        bathrooms: 1,
        genderPreference: "Any Gender",
        amenities: ["Air Conditioning", "Wifi", "Kitchen"],
        contractLength: "1 year",
        description:
            "A cozy apartment perfect for small families or young professionals, located in a vibrant neighborhood.",
        contactPerson: {
            name: "Juan dela Cruz",
            image: "/juan.jpg",
            joinedDate: "January 2020",
        },
        status: "Available",
    },
    {
        id: "2",
        name: "Spacious House in Sampaloc",
        location: "Sampaloc, Manila",
        price: 25000,
        images: ["/room.jpg", "/room.jpg", "/room.jpg"],
        propertyType: "House",
        bedrooms: 3,
        bathrooms: 2,
        genderPreference: "Any Gender",
        amenities: ["Parking", "Laundry", "Security"],
        contractLength: "6 months",
        description:
            "A spacious family home with ample parking and security features, close to schools and markets.",
        contactPerson: {
            name: "Maria Santos",
            image: "/maria.jpg",
            joinedDate: "March 2019",
        },
        status: "Available",
    },
    {
        id: "3",
        name: "Female Bed Space Available",
        location: "Quiapo, Manila",
        price: 5200,
        images: ["/room.jpg", "/room.jpg", "/room.jpg"],
        propertyType: "Bedspace",
        bedrooms: 1,
        bathrooms: 1,
        genderPreference: "Female",
        amenities: ["Wifi"],
        contractLength: "3 months",
        description:
            "Affordable bed space available for female students or young professionals in a safe neighborhood.",
        contactPerson: {
            name: "Lina Reyes",
            image: "/lina.jpg",
            joinedDate: "February 2021",
        },
        status: "Under Maintenance",
    },
    {
        id: "4",
        name: "Shared Room for Rent in Tondo",
        location: "Tondo, Manila",
        price: 4800,
        images: ["/room.jpg", "/room.jpg", "/room.jpg"],
        propertyType: "Bedspace",
        bedrooms: 2,
        bathrooms: 1,
        genderPreference: "Any Gender",
        amenities: ["Laundry"],
        contractLength: "1 month",
        description:
            "Shared room available in a friendly environment, ideal for students or young professionals.",
        contactPerson: {
            name: "Carlos Garcia",
            image: "/carlos.jpg",
            joinedDate: "April 2022",
        },
        status: "Available",
    },
    {
        id: "5",
        name: "Modern Apartment Near UST",
        location: "Sampaloc, Manila",
        price: 18000,
        images: ["/room.jpg", "/room.jpg", "/room.jpg"],
        propertyType: "Apartment",
        bedrooms: 1,
        bathrooms: 1,
        genderPreference: "Any Gender",
        amenities: ["Air Conditioning", "Wifi", "Kitchen"],
        contractLength: "1 year",
        description:
            "A modern apartment with all the amenities you need, located just a short walk from UST.",
        contactPerson: {
            name: "Ana Cruz",
            image: "/ana.jpg",
            joinedDate: "May 2020",
        },
        status: "Available",
    },
    {
        id: "6",
        name: "Budget Bed Space in Ermita",
        location: "Ermita, Manila",
        price: 4000,
        images: ["/room.jpg", "/room.jpg", "/room.jpg"],
        propertyType: "Bedspace",
        bedrooms: 1,
        bathrooms: 1,
        genderPreference: "Male",
        amenities: ["Kitchen", "CCTV"],
        contractLength: "3 months",
        description:
            "Affordable bed space available in Ermita, close to shops and public transport.",
        contactPerson: {
            name: "Mark Lim",
            image: "/mark.jpg",
            joinedDate: "June 2021",
        },
        status: "Occupied",
    },
    {
        id: "7",
        name: "Family House in Intramuros",
        location: "Intramuros, Manila",
        price: 30000,
        images: ["/room.jpg", "/room.jpg", "/room.jpg"],
        propertyType: "House",
        bedrooms: 4,
        bathrooms: 3,
        genderPreference: "Any Gender",
        amenities: ["Air Conditioning", "Wifi", "Laundry"],
        contractLength: "6 months",
        description:
            "A spacious family house with historical charm and modern amenities.",
        contactPerson: {
            name: "Elena Reyes",
            image: "/elena.jpg",
            joinedDate: "July 2018",
        },
        status: "Under Maintenance",
    },
    {
        id: "8",
        name: "Male Bed Space Only in Malate",
        location: "Malate, Manila",
        price: 15000,
        images: ["/room.jpg", "/room.jpg", "/room.jpg"],
        propertyType: "Bedspace",
        bedrooms: 1,
        bathrooms: 1,
        genderPreference: "Male",
        amenities: ["Wifi"],
        contractLength: "1 month",
        description: "Exclusive male bed space in a lively area of Malate.",
        contactPerson: {
            name: "Rico Santos",
            image: "/rico.jpg",
            joinedDate: "August 2020",
        },
        status: "Available",
    },
    {
        id: "9",
        name: "Luxury Apartment Near LRT",
        location: "Sta. Cruz, Manila",
        price: 22000,
        images: ["/room.jpg", "/room.jpg", "/room.jpg"],
        propertyType: "Apartment",
        bedrooms: 2,
        bathrooms: 2,
        genderPreference: "Any Gender",
        amenities: ["Air Conditioning", "Security", "Parking"],
        contractLength: "1 year",
        description:
            "A luxurious apartment with modern finishes and close proximity to public transport.",
        contactPerson: {
            name: "Maria Santos",
            image: "/maria_santos.jpg",
            joinedDate: "September 2017",
        },
        status: "Occupied",
    },
];
